// Generated by scripts/brand/port-visuals.py from the visuals library
// (src/gen_protocols.py). Do not edit by hand.

export type StepKind = "step" | "pause" | "repair" | "safety" | "failure" | "note";

export interface DiagramStep {
  title: string;
  detail: string;
  kind: StepKind;
  badge?: string;
}

export interface ProtocolDiagram {
  when: string;
  steps: DiagramStep[];
  note: { kind: StepKind; text: string } | null;
  outcome: string;
}

export const protocolDiagrams: Record<string, ProtocolDiagram> = {
  "pause-and-return": {
    "when": "Either partner is flooded or shut down: racing heart, tunnel vision, contempt, urge to flee or win.",
    "steps": [
      {
        "title": "Signal",
        "detail": "“I need a pause.” No justification required.",
        "kind": "pause"
      },
      {
        "title": "Time",
        "detail": "Set a return time: “I’ll be ready at ___.”",
        "kind": "pause",
        "badge": "15 min – 24 h"
      },
      {
        "title": "Separate",
        "detail": "Down-regulate: walk, shower, breathe, music. Avoid rehearsing arguments.",
        "kind": "pause"
      },
      {
        "title": "Return",
        "detail": "Reconnect at the agreed time, even briefly, to prove pause, not disappearance.",
        "kind": "repair",
        "badge": "at the agreed time"
      },
      {
        "title": "Restart",
        "detail": "Warmth → Safety (not “where we left off”).",
        "kind": "repair"
      }
    ],
    "note": {
      "kind": "failure",
      "text": "“Later” is not a return time. Always give a clock time."
    },
    "outcome": "Protection without disappearance."
  },
  "60-second-reset": {
    "when": "Co-present, and the conversation has become about winning. Both willing to stop for one minute.",
    "steps": [
      {
        "title": "Stop",
        "detail": "Disengage from winning or solving.",
        "kind": "pause"
      },
      {
        "title": "Name",
        "detail": "“I want to connect, not fight.”",
        "kind": "step"
      },
      {
        "title": "Contact",
        "detail": "Brief touch, if welcome.",
        "kind": "step"
      },
      {
        "title": "Breathe",
        "detail": "Three slow breaths together.",
        "kind": "pause",
        "badge": "3 breaths"
      },
      {
        "title": "Return",
        "detail": "Set a specific time to continue: “Can we talk at ___?”",
        "kind": "repair"
      }
    ],
    "note": {
      "kind": "failure",
      "text": "Always pair stop with return. A reset with no return time is withdrawal."
    },
    "outcome": "Damage stops in one minute; real repair is scheduled."
  },
  "green-rule": {
    "when": "Always, especially when honesty feels costly, or ultimatums, stonewalling, or retaliation appear.",
    "steps": [
      {
        "title": "Name the risk",
        "detail": "One sentence: “This doesn’t feel safe right now.”",
        "kind": "safety"
      },
      {
        "title": "Stop content",
        "detail": "Immediately. No proving.",
        "kind": "failure"
      },
      {
        "title": "Pause + Return",
        "detail": "Activate it with a specific return time.",
        "kind": "pause"
      },
      {
        "title": "Restart",
        "detail": "On return, Warmth → Safety before the original topic.",
        "kind": "repair"
      },
      {
        "title": "Repair the fault",
        "detail": "Repair safety faults with an agreed phrase.",
        "kind": "repair"
      }
    ],
    "note": {
      "kind": "safety",
      "text": "Priority over all content tools. If safety fails, content stops."
    },
    "outcome": "Honesty stays speakable without punishment."
  },
  "system-overlay": {
    "when": "Any sensitive discussion, change request, rupture repair, or joint decision. Also a diagnostic when stuck.",
    "steps": [
      {
        "title": "Warmth",
        "detail": "Warmest true sentence; same team. “I love us, and I’m not trying to fight.”",
        "kind": "step"
      },
      {
        "title": "Safety",
        "detail": "Green Rule: the relationship is not threatened in this moment.",
        "kind": "safety"
      },
      {
        "title": "Expression",
        "detail": "Impact with ownership: “When X happened, I felt Y; the impact was Z.”",
        "kind": "step"
      },
      {
        "title": "Request",
        "detail": "One specific, actionable, time-bound ask.",
        "kind": "step"
      },
      {
        "title": "Alignment",
        "detail": "Who does what by when, plus a review.",
        "kind": "step"
      }
    ],
    "note": {
      "kind": "note",
      "text": "If a conversation collapses, restart from the last intact step."
    },
    "outcome": "Hard conversations produce outcomes, not always/never fights."
  },
  "weekly-reset": {
    "when": "Same day and time each week; also after travel, stress, or distance. A maintenance meeting, not a trial.",
    "steps": [
      {
        "title": "Appreciation",
        "detail": "One specific appreciation each.",
        "kind": "step",
        "badge": "5 min"
      },
      {
        "title": "Care Check-in",
        "detail": "Where supported, where alone? Is the load fair?",
        "kind": "step",
        "badge": "10–15 min"
      },
      {
        "title": "Friction Review",
        "detail": "One small friction each; apply the 2% Rule.",
        "kind": "step",
        "badge": "10–15 min"
      },
      {
        "title": "Requests",
        "detail": "One specific ask each for next week.",
        "kind": "step"
      },
      {
        "title": "Alignment",
        "detail": "One next step + a review time.",
        "kind": "step"
      }
    ],
    "note": {
      "kind": "pause",
      "text": "If either partner is flooded: Pause + Return first, then reschedule."
    },
    "outcome": "Friction stays small and predictable. 30-minute timer."
  },
  "conflict-protocol": {
    "when": "Active conflict or recurring loops, when Warmth is still possible, or after a pause returns you to regulation.",
    "steps": [
      {
        "title": "Check regulation",
        "detail": "Flooded or shut down? Pause + Return first.",
        "kind": "pause"
      },
      {
        "title": "Warmth",
        "detail": "One warm true sentence: “I’m on your team, even though I’m frustrated.”",
        "kind": "step"
      },
      {
        "title": "Safety",
        "detail": "The Alliance is not threatened this moment.",
        "kind": "safety"
      },
      {
        "title": "Expression",
        "detail": "When X, I felt Y; impact Z.",
        "kind": "step"
      },
      {
        "title": "Request",
        "detail": "One specific ask.",
        "kind": "step"
      },
      {
        "title": "Accountability order",
        "detail": "Impact → What would help → Perspective last.",
        "kind": "repair"
      },
      {
        "title": "Proof, if needed",
        "detail": "Behaviour + evidence + window.",
        "kind": "repair"
      },
      {
        "title": "Alignment",
        "detail": "Next step + check-back.",
        "kind": "step"
      }
    ],
    "note": null,
    "outcome": "The loop interrupts without a courtroom."
  },
  "micro-repair": {
    "when": "Tone sharpens, small hurts, residue starting. Full repair feels impossible, but waiting will worsen the Tone Spiral.",
    "steps": [
      {
        "title": "Soften",
        "detail": "Soften tone deliberately (Reciprocal Softness): “Soft reset, my tone.”",
        "kind": "repair"
      },
      {
        "title": "2% move",
        "detail": "2% behavioural and/or 2% ownership: “2%: I can own ___.”",
        "kind": "repair"
      },
      {
        "title": "Side-by-side",
        "detail": "Shift side-by-side if face-to-face is too hot: “Can we walk and talk?”",
        "kind": "step"
      },
      {
        "title": "Acknowledge impact",
        "detail": "One sentence, no “but”.",
        "kind": "repair"
      },
      {
        "title": "Tiny next step",
        "detail": "Or Pause + Return.",
        "kind": "step"
      }
    ],
    "note": {
      "kind": "note",
      "text": "Best on residue under 48 hours old. Deliver within 10 minutes."
    },
    "outcome": "Residue clears before it hardens."
  },
  "proof-protocol": {
    "when": "After any meaningful change request; when “I promise” appears without a plan; ending Hope Fog.",
    "steps": [
      {
        "title": "Behaviour",
        "detail": "Name the change: specific, observable.",
        "kind": "step"
      },
      {
        "title": "Evidence",
        "detail": "Define what counts as met / partial / missed.",
        "kind": "step"
      },
      {
        "title": "Window",
        "detail": "Set start, end, and review ritual.",
        "kind": "step"
      },
      {
        "title": "Track",
        "detail": "Tally or table; facts first at review.",
        "kind": "step"
      },
      {
        "title": "Review",
        "detail": "Extend, adjust, or close; Team Frame on.",
        "kind": "repair"
      },
      {
        "title": "Escalate",
        "detail": "If misses dominate without ownership.",
        "kind": "failure"
      }
    ],
    "note": null,
    "outcome": "Change you can see. Trust moves on evidence, not promises."
  },
  "morning-evening-rhythm": {
    "when": "Every day. Reinstate first after travel, illness, or stress.",
    "steps": [
      {
        "title": "Morning Reset",
        "detail": "Devices down → touch or eye contact → “How are you going into today?” → one intention.",
        "kind": "step",
        "badge": "≤ 5 min"
      },
      {
        "title": "Evening Check-in",
        "detail": "Decompress side-by-side → no logistics → “How did today actually go?” → one specific appreciation.",
        "kind": "step",
        "badge": "first 10 min"
      },
      {
        "title": "Protect the windows",
        "detail": "Phone bowl, or charger elsewhere, during both windows.",
        "kind": "step"
      },
      {
        "title": "Track",
        "detail": "Y/N for 7 days; adjust timing, not intensity.",
        "kind": "step",
        "badge": "7 days"
      }
    ],
    "note": null,
    "outcome": "Predictable daily contact. Drift stays small."
  },
  "intimacy-pact": {
    "when": "Initiating or declining feels tense; intimacy stall; after a trust dent; preventive Structure.",
    "steps": [
      {
        "title": "Partner-First",
        "detail": "Invest in your partner’s experience before only your own.",
        "kind": "step"
      },
      {
        "title": "No penalty",
        "detail": "Agree: a decline carries no cost — no punishing, sulking, or guilt-tripping.",
        "kind": "safety"
      },
      {
        "title": "Warm Decline",
        "detail": "Install Warm Decline + alternative closeness options.",
        "kind": "step"
      },
      {
        "title": "Initiation",
        "detail": "Name initiation preferences: verbal / nonverbal; timing.",
        "kind": "step"
      },
      {
        "title": "Review",
        "detail": "Set a 30-day review, without mid-stream scorekeeping.",
        "kind": "step",
        "badge": "30 days"
      },
      {
        "title": "Safety check",
        "detail": "If contempt or safety issues: repair chapters first.",
        "kind": "failure"
      }
    ],
    "note": null,
    "outcome": "Vulnerability stays safe; the pact holds."
  },
  "trust-recovery": {
    "when": "After betrayal, deception, repeated broken agreements, or any before/after in safety.",
    "steps": [
      {
        "title": "Name the breach",
        "detail": "Clearly, without deflection.",
        "kind": "step"
      },
      {
        "title": "Define the change",
        "detail": "One specific, observable behaviour change.",
        "kind": "step"
      },
      {
        "title": "Set the window",
        "detail": "A meaningful window with review dates.",
        "kind": "step"
      },
      {
        "title": "Track",
        "detail": "Behaviour Window table: facts.",
        "kind": "step",
        "badge": "weekly"
      },
      {
        "title": "Review",
        "detail": "Record first, then feelings; extend, adjust, or close.",
        "kind": "repair"
      },
      {
        "title": "Safety",
        "detail": "If safety is absent, stop and seek appropriate support.",
        "kind": "failure"
      }
    ],
    "note": null,
    "outcome": "Evidence accumulates; the nervous system quiets."
  },
  "consistency-pact": {
    "when": "Weekly personal integrity practice; after emotional promising; alongside shared Proof during rebuild.",
    "steps": [
      {
        "title": "Words",
        "detail": "What do I say I value? Write it.",
        "kind": "step"
      },
      {
        "title": "Intent",
        "detail": "What did I intend this week?",
        "kind": "step"
      },
      {
        "title": "Proof",
        "detail": "What did I actually do? Where was the gap?",
        "kind": "step"
      },
      {
        "title": "Change",
        "detail": "One observable behaviour next week.",
        "kind": "repair"
      },
      {
        "title": "Keep it private",
        "detail": "Unless invited. Privacy protects honesty.",
        "kind": "note"
      },
      {
        "title": "Not a substitute",
        "detail": "Does not replace shared Proof on live breaches.",
        "kind": "failure"
      }
    ],
    "note": null,
    "outcome": "The integrity gap shrinks."
  }
};
