#!/usr/bin/env python3
"""Port the THE ALLIANCE visuals library into app code.

Reads the v2 library at /workspace/alliance-product/visuals (or $VISUALS_DIR)
and writes:
  src/data/visuals/protocol-diagrams.ts   step titles, kinds, timings, outcomes
  src/components/visuals/ProtocolIcon.tsx React line icons (currentColor)
Run: python3 scripts/brand/port-visuals.py
"""
import json, os, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
VIS = Path(os.environ.get("VISUALS_DIR", "/workspace/alliance-product/visuals"))
sys.path.insert(0, str(VIS / "src"))
import gen_protocols  # noqa: E402

# ---- protocol step diagrams -------------------------------------------------
out = {}
for slug, d in gen_protocols.P.items():
    note = None
    if d.get("note"):
        k, t = d["note"]
        note = {"kind": {"caution": "failure"}.get(k, k), "text": t}
    out[slug] = {
        "when": d["when"],
        "steps": [
            {"title": t, "detail": det, "kind": kind, **({"badge": badge} if badge else {})}
            for (t, det, kind, badge) in d["steps"]
        ],
        "note": note,
        "outcome": d["outcome"],
    }

data_dir = ROOT / "src/data/visuals"
data_dir.mkdir(parents=True, exist_ok=True)
(data_dir / "protocol-diagrams.ts").write_text(
    "// Generated by scripts/brand/port-visuals.py from the visuals library\n"
    "// (src/gen_protocols.py). Do not edit by hand.\n\n"
    'export type StepKind = "step" | "pause" | "repair" | "safety" | "failure" | "note";\n\n'
    "export interface DiagramStep {\n  title: string;\n  detail: string;\n  kind: StepKind;\n  badge?: string;\n}\n\n"
    "export interface ProtocolDiagram {\n  when: string;\n  steps: DiagramStep[];\n"
    "  note: { kind: StepKind; text: string } | null;\n  outcome: string;\n}\n\n"
    "export const protocolDiagrams: Record<string, ProtocolDiagram> = "
    + json.dumps(out, ensure_ascii=False, indent=2)
    + ";\n"
)

# ---- icons -------------------------------------------------------------------
def to_jsx(inner: str) -> str:
    inner = re.sub(r'stroke="#[0-9A-Fa-f]{6}"', "", inner)
    inner = re.sub(r'fill="#[0-9A-Fa-f]{6}"', 'fill="currentColor"', inner)
    attr_map = {"fill-opacity": "fillOpacity", "stroke-width": "strokeWidth",
                "stroke-linecap": "strokeLinecap", "stroke-linejoin": "strokeLinejoin"}
    for a, b in attr_map.items():
        inner = inner.replace(a + "=", b + "=")
    inner = re.sub(r"\s+/>", "/>", inner)
    inner = re.sub(r"\s{2,}", " ", inner)
    return inner

icons = {}
for f in sorted((VIS / "svg").glob("icon-*.svg")):
    if f.name == "icon-set-sheet.svg":
        continue
    s = f.read_text()
    m = re.search(r"<g [^>]*>(.*)</g></svg>", s, re.S)
    if not m:
        continue
    key = f.stem.replace("icon-protocol-", "").replace("icon-section-", "section-")
    icons[key] = to_jsx(m.group(1))

lines = [
    "// Generated by scripts/brand/port-visuals.py from the visuals library",
    "// (svg/icon-*.svg): the v2 24-grid arch-built family, stroke 1.5, round caps",
    "// and joins, with the mark's filled leaf. Drawn in currentColor. Do not edit by hand.",
    "",
    "const paths: Record<string, React.ReactNode> = {",
]
for k, v in icons.items():
    lines.append(f'  "{k}": <>{v}</>,')
lines += [
    "};",
    "",
    "export const protocolIconSlugs = Object.keys(paths);",
    "",
    "export function ProtocolIcon({",
    "  slug,",
    "  size = 24,",
    "  strokeWidth = 1.5,",
    '  className = "",',
    "  title,",
    "}: {",
    "  slug: string;",
    "  size?: number;",
    "  strokeWidth?: number;",
    "  className?: string;",
    "  title?: string;",
    "}) {",
    "  const body = paths[slug];",
    "  if (!body) return null;",
    "  return (",
    "    <svg",
    '      viewBox="0 0 24 24"',
    "      width={size}",
    "      height={size}",
    "      className={className}",
    '      fill="none"',
    '      stroke="currentColor"',
    "      strokeWidth={strokeWidth}",
    '      strokeLinecap="round"',
    '      strokeLinejoin="round"',
    '      role={title ? "img" : undefined}',
    "      aria-label={title}",
    "      aria-hidden={title ? undefined : true}",
    '      focusable="false"',
    "    >",
    "      {body}",
    "    </svg>",
    "  );",
    "}",
    "",
]
comp_dir = ROOT / "src/components/visuals"
comp_dir.mkdir(parents=True, exist_ok=True)
(comp_dir / "ProtocolIcon.tsx").write_text("\n".join(lines))
print(f"ported {len(out)} protocol diagrams, {len(icons)} icons")
