// Generated by scripts/brand/port-visuals.py from the visuals library
// (svg/icon-*.svg): the v2 24-grid arch-built family, stroke 1.5, round caps
// and joins, with the mark's filled leaf. Drawn in currentColor. Do not edit by hand.

const paths: Record<string, React.ReactNode> = {
  "60-second-reset": <><path d="M5.2 21V12.8A6.8 6.8 0 0 1 18.8 12.8V21Z"/><path d="M10 2.8H14M12 2.8V6"/><path d="M18.2 6.6L19.6 5.2"/><path d="M12 10.47C13.57 11.94 14.1 13.2 14.1 14.14A2 2 0 0 1 9.9 14.14C9.9 13.2 10.43 11.94 12 10.47Z" fill="currentColor" stroke="none"/><path d="M12 16.2V18"/></>,
  "conflict-protocol": <><path d="M2.5 6C8 6 9.5 12 13 12H21.5"/><path d="M2.5 18C5.2 18 6.8 16.4 8.2 14.6"/><path d="M9.8 12.3C10.7 11.2 11.6 10.4 12.7 10"/><path d="M18.5 9L21.5 12L18.5 15"/></>,
  "consistency-pact": <><path d="M12 3.5A8.5 8.5 0 0 1 20.5 12"/><path d="M20.5 12A8.5 8.5 0 0 1 12 20.5"/><path d="M12 20.5A8.5 8.5 0 0 1 3.5 12"/><path d="M3.5 12A8.5 8.5 0 0 1 9.4 3.9"/><path d="M7.4 2.5L9.6 3.9L8.3 6.2"/><path d="M12 9.4C13.5 10.8 14 12 14 12.9A2 2 0 0 1 10 12.9C10 12 10.5 10.8 12 9.4Z" fill="currentColor" stroke="none"/></>,
  "green-rule": <><path d="M4.5 8.8A7.5 7.5 0 0 1 19.5 8.8V12C19.5 16.4 16.3 19.6 12 21.4 7.7 19.6 4.5 16.4 4.5 12Z"/><path d="M12 8C14.2 10.1 15 12 15 13.6 15 15.5 13.6 16.8 12 17.8 10.4 16.8 9 15.5 9 13.6 9 12 9.8 10.1 12 8Z"/></>,
  "intimacy-pact": <><path d="M2.5 19V9.5A5 5 0 0 1 12.5 9.5V14"/><path d="M11.5 14V9.5A5 5 0 0 1 21.5 9.5V19"/><path d="M12 12.2C13.6 13.8 14.2 15.2 14.2 16.3 14.2 17.8 13.2 18.8 12 19.6 10.8 18.8 9.8 17.8 9.8 16.3 9.8 15.2 10.4 13.8 12 12.2Z" fill="currentColor" stroke="none"/></>,
  "micro-repair": <><path d="M3.5 19V11A4.5 4.5 0 0 1 12.5 11V13.2"/><path d="M12.5 16.4V19"/><path d="M20.5 5V13A4.5 4.5 0 0 1 11.5 13V5"/></>,
  "morning-evening-rhythm": <><path d="M2 14H22"/><path d="M5.5 14A6.5 6.5 0 0 1 18.5 14"/><path d="M12 3.2V5M5.6 5.8L6.8 7M18.4 5.8L17.2 7"/><path d="M8 17.5A4 4 0 0 0 16 17.5"/><path d="M12 8.72C13.2 9.84 13.6 10.8 13.6 11.52A2 2 0 0 1 10.4 11.52C10.4 10.8 10.8 9.84 12 8.72Z" fill="currentColor" stroke="none"/></>,
  "pause-and-return": <><path d="M5.5 3H18.5M5.5 21H18.5"/><path d="M7.5 3V6.5A4.5 4.5 0 0 0 16.5 6.5V3"/><path d="M7.5 21V17.5A4.5 4.5 0 0 1 16.5 17.5V21"/><path d="M12 16.32C13.2 17.44 13.6 18.4 13.6 19.12A2 2 0 0 1 10.4 19.12C10.4 18.4 10.8 17.44 12 16.32Z" fill="currentColor" stroke="none"/></>,
  "proof-protocol": <><path d="M4.5 21.5V9.5A7.5 7.5 0 0 1 19.5 9.5V21.5Z"/><path d="M8.6 11.4L11 13.8L15.6 9"/><path d="M8 17.2H16"/></>,
  "system-overlay": <><path d="M3 21V12A9 9 0 0 1 21 12V21"/><path d="M7 21V12.5A5 5 0 0 1 17 12.5V21"/><path d="M3 21H21"/><path d="M12 15C13.5 16.4 14 17.6 14 18.5A2 2 0 0 1 10 18.5C10 17.6 10.5 16.4 12 15Z" fill="currentColor" stroke="none"/></>,
  "trust-recovery": <><path d="M6 21.5V9A6 6 0 0 1 18 9V21.5"/><path d="M6 17.5H18M6 13.2H18"/><path d="M12 6.12C13.2 7.24 13.6 8.2 13.6 8.92A2 2 0 0 1 10.4 8.92C10.4 8.2 10.8 7.24 12 6.12Z" fill="currentColor" stroke="none"/></>,
  "weekly-reset": <><path d="M4 21V9A8 8 0 0 1 20 9V21Z"/><path d="M4 12.5H20"/><path d="M15 16.6A3 3 0 1 1 13.9 14.3"/><path d="M14.2 12.9L14.1 14.5L15.7 14.6"/><path d="M12 4.25C13.12 5.3 13.5 6.2 13.5 6.88A2 2 0 0 1 10.5 6.88C10.5 6.2 10.88 5.3 12 4.25Z" fill="currentColor" stroke="none"/></>,
  "section-activity": <><path d="M12 21.5C8.5 18 6.5 14.5 6.5 10.5V7.5A5.5 5.5 0 0 1 17.5 7.5V10.5C17.5 14.5 15.5 18 12 21.5Z"/><path d="M12 21.5V13"/><circle cx="12" cy="10.6" r="1.3" fill="currentColor" stroke="none"/></>,
  "section-caution": <><path d="M4 21.5V13C4 8.4 7.2 4.6 12 2.5 16.8 4.6 20 8.4 20 13V21.5Z"/><path d="M12 9.5V15"/><circle cx="12" cy="18" r="1.05" fill="currentColor" stroke="none"/></>,
  "section-concept": <><path d="M7.2 16V9.2A4.8 4.8 0 0 1 16.8 9.2V16Z"/><path d="M9 19H15M10.2 21.5H13.8"/><path d="M12 8.73C13.43 10.06 13.9 11.2 13.9 12.05A2 2 0 0 1 10.1 12.05C10.1 11.2 10.57 10.06 12 8.73Z" fill="currentColor" stroke="none"/></>,
  "section-not-working": <><path d="M4.5 21V10.5A7.5 7.5 0 0 1 10.2 3.2"/><path d="M13.8 3.2A7.5 7.5 0 0 1 19.5 10.5V21"/><path d="M9.2 12.2L14.8 17.8M14.8 12.2L9.2 17.8"/></>,
  "section-say-this": <><path d="M3 17V9A6 6 0 0 1 9 3H15A6 6 0 0 1 21 9V11A6 6 0 0 1 15 17H10L5.5 21V17Z"/><path d="M9.5 12.41C10.78 11.22 11.2 10.2 11.2 9.43A2 2 0 0 0 7.8 9.43C7.8 10.2 8.22 11.22 9.5 12.41Z" fill="currentColor" stroke="none"/><path d="M14.5 12.41C15.78 11.22 16.2 10.2 16.2 9.43A2 2 0 0 0 12.8 9.43C12.8 10.2 13.22 11.22 14.5 12.41Z" fill="currentColor" stroke="none"/></>,
  "section-steps": <><path d="M3 8.5V5.8A2 2 0 0 1 7 5.8V8.5Z"/><path d="M3 15.5V12.8A2 2 0 0 1 7 12.8V15.5Z"/><path d="M3 22V19.3A2 2 0 0 1 7 19.3V22Z"/><path d="M10.5 7H21M10.5 14H21M10.5 21H17.5"/></>,
  "section-tool": <><path d="M5 12V7.5A4 4 0 0 1 13 7.5V12Z"/><path d="M9 12V21.5"/><path d="M9 17.5H12M9 20.5H13"/><path d="M17 21.5V11.5M15 13.5L17 11.5L19 13.5"/></>,
  "section-when-to-use": <><path d="M2.5 21.5H21.5"/><path d="M5.5 21.5V10.5A6.5 6.5 0 0 1 18.5 10.5V21.5"/><path d="M10.8 2.5H13.2L12.7 4.8H11.3Z" fill="currentColor"/><path d="M12 13.47C13.57 14.94 14.1 16.2 14.1 17.14A2 2 0 0 1 9.9 17.14C9.9 16.2 10.43 14.94 12 13.47Z" fill="currentColor" stroke="none"/></>,
  "section-working": <><path d="M4.5 21V10.5A7.5 7.5 0 0 1 19.5 10.5V21Z"/><path d="M8.6 14L11 16.4L15.6 11.6"/></>,
};

export const protocolIconSlugs = Object.keys(paths);

export function ProtocolIcon({
  slug,
  size = 24,
  strokeWidth = 1.5,
  className = "",
  title,
}: {
  slug: string;
  size?: number;
  strokeWidth?: number;
  className?: string;
  title?: string;
}) {
  const body = paths[slug];
  if (!body) return null;
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      className={className}
      fill="none"
      stroke="currentColor"
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
      role={title ? "img" : undefined}
      aria-label={title}
      aria-hidden={title ? undefined : true}
      focusable="false"
    >
      {body}
    </svg>
  );
}
