// Generated by scripts/brand/port-visuals.py from the visuals library
// (svg/icon-*.svg). Line icons drawn in currentColor. Do not edit by hand.

const paths: Record<string, React.ReactNode> = {
  "60-second-reset": <><circle cx="12" cy="13.5" r="7.5"/><path d="M10 2.8h4M12 2.8v3.2M12 13.5V9.6M12 13.5l2.6 1.6M18.4 6.6l1.3-1.3"/></>,
  "conflict-protocol": <><path d="M3 6h4.5c2.2 0 3.3 1.2 4.5 3l1.2 2"/><path d="M3 18h4.5c2.2 0 3.3-1.2 4.5-3l1.2-2"/><path d="M13.2 12H21"/><path d="M18 9l3 3-3 3"/></>,
  "consistency-pact": <><circle cx="12" cy="12" r="7.8"/><circle cx="12" cy="4.2" r="1.5" fill="currentColor"/><circle cx="19.8" cy="12" r="1.5" fill="currentColor"/><circle cx="12" cy="19.8" r="1.5" fill="currentColor"/><circle cx="4.2" cy="12" r="1.5" fill="currentColor"/></>,
  "green-rule": <><path d="M12 2.8l7.5 2.9v5.6c0 4.6-3.1 8.3-7.5 9.9-4.4-1.6-7.5-5.3-7.5-9.9V5.7z"/><path d="M8.6 12.2l2.4 2.4 4.6-4.8"/></>,
  "intimacy-pact": <><path d="M12 7.6a5.6 5.6 0 0 1 0 8.8 5.6 5.6 0 0 1 0-8.8z" fill="currentColor" fillOpacity=".22" stroke="none"/><circle cx="8.6" cy="12" r="5.6"/><circle cx="15.4" cy="12" r="5.6"/></>,
  "micro-repair": <><path d="M2.5 12.5l2-4.5 2 9 2-9 1.8 4.5C11.6 15.8 13.4 16 15 12.5S18.6 8.8 21.5 12.5"/></>,
  "morning-evening-rhythm": <><path d="M2.5 19.5h19"/><path d="M4.5 19.5a4.5 4.5 0 0 1 9 0"/><path d="M9 11.8v-1.8M4.1 14.1l-1.2-1.2M13.9 14.1l1.2-1.2"/><path d="M18.6 3.5a3.8 3.8 0 1 0 2.9 6.2 3.1 3.1 0 0 1-2.9-6.2z"/></>,
  "pause-and-return": <><path d="M19.5 12a7.5 7.5 0 1 1-2.2-5.3"/><path d="M19.8 3.8v3.6h-3.6"/><path d="M10 9.2v5.6M14 9.2v5.6"/></>,
  "proof-protocol": <><rect x="4.5" y="3" width="15" height="18" rx="2.5"/><path d="M8 8.5l1.4 1.4 2.4-2.6M13.8 8.8h2.6M8 14l1.4 1.4 2.4-2.6M13.8 14.3h2.6"/></>,
  "system-overlay": <><path d="M3.5 20.5h3.4v-3.4h3.4v-3.4h3.4v-3.4h3.4V6.9h3.4"/><circle cx="20.5" cy="3.9" r="1.4"/></>,
  "trust-recovery": <><path d="M7 3v18M17 3v18"/><path d="M7 17.5h10M7 12h10M7 6.5h10"/></>,
  "weekly-reset": <><rect x="3.5" y="5" width="17" height="15.5" rx="2.5"/><path d="M3.5 9.5h17M8 3v4M16 3v4"/><path d="M15.2 14.8a3.2 3.2 0 1 1-1-2.3"/><path d="M14.6 11.4v1.6h-1.6"/></>,
  "section-activity": <><path d="M15.5 4.5l4 4L9 19l-5 1 1-5z"/><path d="M13.2 6.8l4 4"/></>,
  "section-caution": <><path d="M12 3.8L21 19.5H3z"/><path d="M12 10v4.3"/><circle cx="12" cy="17" r=".6" fill="currentColor"/></>,
  "section-concept": <><path d="M9 17.5h6M9.8 20.5h4.4"/><path d="M12 3.5a6 6 0 0 0-3.6 10.8c.5.4.8 1 .8 1.6v1.6h5.6v-1.6c0-.6.3-1.2.8-1.6A6 6 0 0 0 12 3.5z"/></>,
  "section-not-working": <><circle cx="12" cy="12" r="8.5"/><path d="M9 9l6 6M15 9l-6 6"/></>,
  "section-say-this": <><path d="M4 5.5h16a1.5 1.5 0 0 1 1.5 1.5v8.5a1.5 1.5 0 0 1-1.5 1.5H11l-4.5 3.5V17H4a1.5 1.5 0 0 1-1.5-1.5V7A1.5 1.5 0 0 1 4 5.5z"/><path d="M8.5 9.5v2.2M11 9.5v2.2M13.5 9.5h3M13.5 12.5h2"/></>,
  "section-steps": <><circle cx="5.5" cy="6" r="1.8"/><circle cx="5.5" cy="12" r="1.8"/><circle cx="5.5" cy="18" r="1.8"/><path d="M10 6h10M10 12h10M10 18h7"/></>,
  "section-tool": <><path d="M14.5 4.2a4.6 4.6 0 0 0-5.3 6.2L3.8 15.8a1.9 1.9 0 0 0 0 2.7l1.7 1.7a1.9 1.9 0 0 0 2.7 0l5.4-5.4a4.6 4.6 0 0 0 6.2-5.3l-2.9 2.9-3-.7-.7-3z"/></>,
  "section-when-to-use": <><path d="M5 21V3.5"/><path d="M5 4h11.5l-2.5 4 2.5 4H5"/></>,
  "section-working": <><circle cx="12" cy="12" r="8.5"/><path d="M8.2 12.3l2.6 2.6 5-5.3"/></>,
};

export const protocolIconSlugs = Object.keys(paths);

export function ProtocolIcon({
  slug,
  size = 24,
  strokeWidth = 1.75,
  className = "",
  title,
}: {
  slug: string;
  size?: number;
  strokeWidth?: number;
  className?: string;
  title?: string;
}) {
  const body = paths[slug];
  if (!body) return null;
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      className={className}
      fill="none"
      stroke="currentColor"
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
      role={title ? "img" : undefined}
      aria-label={title}
      aria-hidden={title ? undefined : true}
      focusable="false"
    >
      {body}
    </svg>
  );
}
